// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Article is the predicate function for article builders.
type Article func(*sql.Selector)

// Blog is the predicate function for blog builders.
type Blog func(*sql.Selector)

// Summary is the predicate function for summary builders.
type Summary func(*sql.Selector)
