// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package server

import (
	"github.com/quanee/go-training/week4/internal/dao"
	"github.com/quanee/go-training/week4/internal/service"
)

// Injectors from wire.go:

func InitializeServer() (*Server, func(), error) {
	db, cleanup, err := dao.NewDB()
	if err != nil {
		return nil, nil, err
	}
	daoDao := dao.NewDao(db)
	serviceService := service.NewService(daoDao)
	server := NewServer(serviceService)
	return server, func() {
		cleanup()
	}, nil
}
