// Code generated by entc, DO NOT EDIT.

package ent

import (
	"blog/internal/data/ent/article"
	"blog/internal/data/ent/blog"
	"blog/internal/data/ent/schema"
	"blog/internal/data/ent/summary"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	articleFields := schema.Article{}.Fields()
	_ = articleFields
	// articleDescContent is the schema descriptor for content field.
	articleDescContent := articleFields[1].Descriptor()
	// article.DefaultContent holds the default value on creation for the content field.
	article.DefaultContent = articleDescContent.Default.(string)
	// articleDescID is the schema descriptor for id field.
	articleDescID := articleFields[0].Descriptor()
	// article.IDValidator is a validator for the "id" field. It is called by the builders before save.
	article.IDValidator = articleDescID.Validators[0].(func(int) error)
	blogFields := schema.Blog{}.Fields()
	_ = blogFields
	// blogDescTitle is the schema descriptor for title field.
	blogDescTitle := blogFields[1].Descriptor()
	// blog.DefaultTitle holds the default value on creation for the title field.
	blog.DefaultTitle = blogDescTitle.Default.(string)
	// blogDescContent is the schema descriptor for content field.
	blogDescContent := blogFields[2].Descriptor()
	// blog.DefaultContent holds the default value on creation for the content field.
	blog.DefaultContent = blogDescContent.Default.(string)
	// blogDescID is the schema descriptor for id field.
	blogDescID := blogFields[0].Descriptor()
	// blog.IDValidator is a validator for the "id" field. It is called by the builders before save.
	blog.IDValidator = blogDescID.Validators[0].(func(int) error)
	summaryFields := schema.Summary{}.Fields()
	_ = summaryFields
	// summaryDescTitle is the schema descriptor for title field.
	summaryDescTitle := summaryFields[1].Descriptor()
	// summary.DefaultTitle holds the default value on creation for the title field.
	summary.DefaultTitle = summaryDescTitle.Default.(string)
	// summaryDescID is the schema descriptor for id field.
	summaryDescID := summaryFields[0].Descriptor()
	// summary.IDValidator is a validator for the "id" field. It is called by the builders before save.
	summary.IDValidator = summaryDescID.Validators[0].(func(int) error)
}
