// Code generated by entc, DO NOT EDIT.

package ent

import (
	"blog/internal/data/ent/summary"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// Summary is the model entity for the Summary schema.
type Summary struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Summary) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case summary.FieldID:
			values[i] = new(sql.NullInt64)
		case summary.FieldTitle:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Summary", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Summary fields.
func (s *Summary) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case summary.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case summary.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				s.Title = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Summary.
// Note that you need to call Summary.Unwrap() before calling this method if this Summary
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Summary) Update() *SummaryUpdateOne {
	return (&SummaryClient{config: s.config}).UpdateOne(s)
}

// Unwrap unwraps the Summary entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Summary) Unwrap() *Summary {
	tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Summary is not a transactional entity")
	}
	s.config.driver = tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Summary) String() string {
	var builder strings.Builder
	builder.WriteString("Summary(")
	builder.WriteString(fmt.Sprintf("id=%v", s.ID))
	builder.WriteString(", title=")
	builder.WriteString(s.Title)
	builder.WriteByte(')')
	return builder.String()
}

// Summaries is a parsable slice of Summary.
type Summaries []*Summary

func (s Summaries) config(cfg config) {
	for _i := range s {
		s[_i].config = cfg
	}
}
